language: node_js
node_js:
    - "20.2.0"
dist: focal
jobs:
    - stage: build
      name: "Install & Build"
      resource_class: large 
      script:
        - npm ci && npm i --force mirador@"^3.3.0" --no-save
        - export NODE_OPTIONS=--max_old_space_size=8192 
        - npm run build
